name = "ArgParseLite"
uuid = "14f05705-a79b-436f-9555-dabef2f39a84"
authors = ["Kevin Bonham", "PhD"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
